Assi 10
shrinker03/NamasteReactBootcamp pull request #7
Opened 2022-12-19 03:16 UTC by shrinker03

2022-12-21 17:24 UTC, Pujarini requested changes
Do connect regarding useEffect usage in ThemeContext

2022-12-21 17:24 UTC, Pujarini commented on namate-dev-assignment/src/App.js
> +import React, { lazy, Suspense } from 'react';
remove import React from 'react'

2022-12-21 17:24 UTC, Pujarini commented on namate-dev-assignment/src/App.js
> +const ThemeContextProvider = lazy(() => import('./Contexts/ThemeContextProvider'));
Why are lazy loading ThemeContextProvider?

2022-12-21 17:24 UTC, Pujarini commented on namate-dev-assignment/src/App.js
> +const ThemeContextProvider = lazy(() => import('./Contexts/ThemeContextProvider'));
Instead you need to lazy load app

2022-12-21 17:24 UTC, Pujarini commented on namate-dev-assignment/src/Components/Card.jsx
>          <div>{bio}</div>
you can try span

2022-12-21 17:24 UTC, Pujarini commented on namate-dev-assignment/src/Components/Header.jsx
> +              xmlns="http://www.w3.org/2000/svg"
save svg in different files and import here

2022-12-21 17:24 UTC, Pujarini commented on namate-dev-assignment/src/Contexts/ThemeContextProvider.js
> +  useEffect(() => {
curious about this.

2022-12-22 12:58 UTC, merged

2022-12-23 09:01 UTC, ap221882 reviewed
Reviewed. Kudos!

2022-12-23 09:01 UTC, ap221882 commented on namate-dev-assignment/package.json
> +    "lint:fix": "eslint --fix",
Because of you I had to learn how to configure eslint and prettier. Kudos!

2022-12-23 09:01 UTC, ap221882 commented on namate-dev-assignment/src/Components/Card.jsx
> +        <hr className="hr" />
avoid using hr/br without having any semantic usecase.

2022-12-23 09:01 UTC, ap221882 commented on namate-dev-assignment/src/Components/Card.jsx
> +        style={{ textDecoration: 'none', display: 'flex', justifyContent: 'center' }}
avoid using inline styling. decreases readability.

2022-12-23 09:01 UTC, ap221882 commented on namate-dev-assignment/src/Components/Card.jsx
> +      </div>
so many divs, use section, article, main, header etc. Will also help in selecting using css

2022-12-23 09:01 UTC, ap221882 commented on namate-dev-assignment/src/Components/RouteError.jsx
> +      <button className="go-back-button" onClick={() => navigate(-1)}>
Appreciated.

2022-12-23 09:01 UTC, ap221882 commented on namate-dev-assignment/src/Components/RouteError.jsx
> +        Go Back
have useRouteError's use too for meaningful errors

2022-12-23 09:01 UTC, ap221882 commented on namate-dev-assignment/src/Contexts/ThemeContextProvider.js
> +    document.body.style.backgroundColor = backgroundColor;
This is fine. But try to do this React's way(declarative and inside root).

2022-12-23 09:01 UTC, ap221882 commented on namate-dev-assignment/src/Hooks/useFilterHook.js
> +    if (data[i][filterFrom]?.trim().toLowerCase().includes(toFilter?.trim().toLowerCase())) {
avoid for loops, use forEach, map, reduce etc. They are more readable.